In [57]:

import yfinance as yf
import numpy as np
import pandas as pd


In [58]:

data = yf.download('RGTI', start='2025-04-11', end='2025-04-28')


[*********************100%***********************]  1 of 1 completed

1 Failed download:
['RGTI']: YFRateLimitError('Too Many Requests. Rate limited. Try after a while.')


In [56]:

data


Empty DataFrame
Columns: [(Adj Close, RGTI), (Close, RGTI), (High, RGTI), (Low, RGTI), (Open, RGTI), (Volume, RGTI)]
Index: []

In [29]:

data["daily_return"] = data["Close"].pct_change()
data["state"] = np.where(data["daily_return"] >= 0, "up", "down")


In [30]:

data


Price            Close        High         Low        Open     Volume  \
Ticker             SPY         SPY         SPY         SPY        SPY   
Date                                                                    
2010-01-04   85.768448   85.813854   84.391067   85.041918  118944600   
2010-01-05   85.995445   86.033288   85.405140   85.715432  111579900   
2010-01-06   86.056030   86.267934   85.844126   85.912236  116074400   
2010-01-07   86.419281   86.525233   85.654909   85.897085  131091100   
2010-01-08   86.706863   86.744706   86.018176   86.192237  126402800   
...                ...         ...         ...         ...        ...   
2022-04-14  419.018188  425.660613  418.912890  424.531188   97869500   
2022-04-18  419.190430  420.894104  416.931608  418.080165   66002500   
2022-04-19  425.957306  426.684698  418.912877  419.085152   77821000   
2022-04-20  425.641479  428.378862  424.464239  427.756739   65224400   
2022-04-21  419.276611  430.714224  418.357783  429.307254   85417300   

Price      daily_return state  
Ticker                         
Date                           
2010-01-04          NaN  down  
2010-01-05     0.002647    up  
2010-01-06     0.000705    up  
2010-01-07     0.004221    up  
2010-01-08     0.003328    up  
...                 ...   ...  
2022-04-14    -0.012452  down  
2022-04-18     0.000411    up  
2022-04-19     0.016143    up  
2022-04-20    -0.000741  down  
2022-04-21    -0.014954  down  

[3097 rows x 7 columns]

In [41]:

up_counts = len(data[data["state"] == "up"])
down_counts = len(data[data["state"] == "down"])

up_to_up = len(data[(data["state"] == "up") & (data["state"].shift(-1) == "up")]) / len(data[data["state"] == "up"])
down_to_up = len(data[(data["state"] == "up") & (data["state"].shift(-1) == "down")]) / len(data[data["state"] == "up"])
up_to_down = len(data[(data["state"] == "down") & (data["state"].shift(-1) == "up")]) / len(data[data["state"] == "down"])
down_to_down = len(data[(data["state"] == "down") & (data["state"].shift(-1) == "down")]) / len(data[data["state"] == "down"])

transition_matrix = pd.DataFrame({
    "up": [up_to_up, up_to_down],
    "down": [down_to_up, down_to_down]
}, index=["up", "down"])



In [59]:
transition_matrix

up      down
up    0.546767  0.453233
down  0.575092  0.424176

In [64]:
M_t = np.array([[.547, .453],[.575, .425]])
M_t

array([[0.547, 0.453],
       [0.575, 0.425]])

In [62]:
from numpy.linalg import matrix_power as mp

In [66]:
M_t_2d = mp(M_t, 2)
M_t_2d

array([[0.559684, 0.440316],
       [0.5589  , 0.4411  ]])

In [1]:

import yfinance as yf
import numpy as np
import pandas as pd

data = yf.download('RGTI', start='2025-04-11', end='2025-04-28')

data["daily_return"] = data["Close"].pct_change()
data["state"] = np.where(data["daily_return"] >= 0, "up", "down")

up_counts = len(data[data["state"] == "up"])
down_counts = len(data[data["state"] == "down"])

up_to_up = len(data[(data["state"] == "up") & (data["state"].shift(-1) == "up")]) / len(data[data["state"] == "up"])
down_to_up = len(data[(data["state"] == "up") & (data["state"].shift(-1) == "down")]) / len(data[data["state"] == "up"])
up_to_down = len(data[(data["state"] == "down") & (data["state"].shift(-1) == "up")]) / len(data[data["state"] == "down"])
down_to_down = len(data[(data["state"] == "down") & (data["state"].shift(-1) == "down")]) / len(data[data["state"] == "down"])

transition_matrix = pd.DataFrame({
    "up": [up_to_up, up_to_down],
    "down": [down_to_up, down_to_down]
}, index=["up", "down"])

M_t = np.array([[.547, .453],[.575, .425]])
M_t


YF.download() has changed argument auto_adjust default to True


[*********************100%***********************]  1 of 1 completed


array([[0.547, 0.453],
       [0.575, 0.425]])